POST http://172.17.12.63:3000/api/auth/login
Content-Type: application/json

{
  "email": "superadmin@company.local",
  "password": "123456"
}
###yya
POST http://172.17.12.63:3000/api/assets/1/lifecycle
Content-Type: application/json

{
  "action_name": "DEPLOYED",
  "from_location": "Warehouse",
  "to_location": "Finance",
  "notes": "Assigned to Finance user"
}
###
GET http://172.17.12.63:3000/api/assets/1/lifecycle
Content-Type: application/json